services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - db

  laravel:
    build:
      context: ./server
    container_name: laravel
    restart: unless-stopped
    volumes:
      - ./server:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: appdb
      DB_USERNAME: appuser
      DB_PASSWORD: apppass

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./server/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./server:/var/www/html
    depends_on:
      - laravel

  web:
    build:
      context: ./web
    container_name: nextjs
    restart: unless-stopped
    volumes:
      - ./web:/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    depends_on:
      - laravel

volumes:
  db_data:
